server:
  port: 8080

spring:
  datasource:
    username: root
    password: d188059xs
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
indexing-settings:
  sites:
      - url: https://volochek.life
        name: Вышний Волочек
      - url: https://www.lutherancathedral.ru
        name: КАФЕДРАЛЬНЫЙ СОБОР СВЯТЫХ ПЕТРА И ПАВЛА
      - url: https://dimonvideo.ru
        name: DimonVideo
jsoup:
  user-agent: SolasSearchBot
  referrer: http://www.google.com
  timeout-min: 50
  timeout-max: 150